# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
